# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.4.4"
asphalt = "jackTabsCode/asphalt@0.9.1"
mantle = "blake-mealey/mantle@0.11.18"
lune = "lune-org/lune@0.8.9"
wally = "UpliftGames/wally@0.3.2"
