[package]
name = "rootentry/lockridge"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
BufferUtil = "sleitnick/buffer-util@0.3.1"
Promise = "evaera/promise@4.0.0"
Knit = "sleitnick/knit@1.7.0"
BasicState = "csqrl/basicstate@0.2.6"
Component = "sleitnick/component@2.4.8"
Concur = "sleitnick/concur@0.1.2"
Input = "sleitnick/input@2.3.0"
Trove = "sleitnick/trove@1.3.0"
Shake = "sleitnick/shake@1.1.0"
TaskQueue = "sleitnick/task-queue@1.0.0"
Signal = "sleitnick/signal@2.0.1"
PID = "sleitnick/pid@2.1.0"
Silo = "sleitnick/silo@0.2.0"
ColourUtils = "csqrl/colour-utils@^1.1.0"
Tree = "sleitnick/tree@1.1.0"
TypedRemote = "sleitnick/typed-remote@0.1.0"
WaitFor = "sleitnick/wait-for@1.0.0"
TableUtil = "sleitnick/table-util@1.2.1"
Symbol = "sleitnick/symbol@2.0.1"
Streamable = "sleitnick/streamable@1.2.4"

[server-dependencies]
Cmdr = "evaera/cmdr@1.8.4"

[dev-dependencies]
# Dev dependencies can be server or shared but are only needed during development.
testez = "roblox/testez@0.4.1"
