return {
	Categories = {
		[1] = {
			Name = "Firearms",
			Icon = "rbxassetid://10415924465",
			Items = {
				"G21",
				"AR15",
				"Shotgun",
			},
		},
		[2] = {
			Name = "Magazines",
			Icon = "rbxassetid://10463422814",
			Items = {
				"Mag9mm",
				"Mag556",
				"Mag12G",
			},
		},
		[3] = {
			Name = "Equipment",
			Icon = "rbxassetid://10415920151",
			Items = {
				"TBaton",
				"Taser",
				"Handcuffs",
			},
		},
		[4] = {
			Type = "Divider",
		},
		[5] = {
			Name = "Saved Loadouts",
			Icon = "rbxassetid://10415898158",
			Bypass = true,
		},
		[6] = {
			Name = "Save Loadout",
			Icon = "rbxassetid://10415902869",
		},
	},
}
