local Teams = {
	{
		Name = "Tourist",
		Idx = 1,

		TeamColor = BrickColor.new("Gold"),
		Default = true,
		Meta = {
			Priority = 2,
		},
	},
	{
		Name = "Resident",
		Idx = 2,

		TeamColor = BrickColor.new("Slime green"),
	},
	{
		Name = "Sheriff's Office",
		Idx = 3,
		LEO = true,
		TeamColor = BrickColor.new("Dark taupe"),
		Meta = {
			Channel = "Global",
		},
	},
	{
		Name = "Courts",
		Idx = 4,

		TeamColor = BrickColor.new("Parsley green"),
	},
	{
		Name = "Burswell Police",
		Idx = 5,
		LEO = true,

		TeamColor = BrickColor.new("Steel blue"),
	},
	{
		Name = "Clemson Police",
		Idx = 6,
		LEO = true,

		TeamColor = BrickColor.new("Earth blue"),
	},

	{
		Name = "Oswell Fire Department",
		Idx = 7,
		TeamColor = BrickColor.new("Crimson"),
	},
	{
		Name = "State Police",
		Idx = 8,
		LEO = true,

		TeamColor = BrickColor.new("Navy blue"),
	},
	{
		Name = "National Guard",
		Idx = 9,
		TeamColor = BrickColor.new("Bright red"),
	},
	{
		Name = "State Government",
		Idx = 10,

		TeamColor = BrickColor.new("Parsley green"),
	},
	{
		Name = "Department of Justice",
		Idx = 11,
		TeamColor = BrickColor.new("Brown"),
	},
	{
		Name = "Department of State",
		Idx = 12,
		TeamColor = BrickColor.new("Neon orange"),
	},
	{
		Name = "Prisoner",
		Idx = 13,
		TeamColor = BrickColor.new("Deep orange"),
	},
	{
		Name = "ILET",
		Idx = 14,
		TeamColor = BrickColor.new("Dark stone grey"),
	},
}

return Teams
