return {
	LILET = {
		[1] = {
			Id = 7325066,
			Name = "Uniforms",
			Pants = "http://www.roblox.com/asset/?id=6202578412",
			Items = {
				["Polo"] = {
					["190-230"] = "http://www.roblox.com/asset/?id=10341380662",
					["235"] = "http://www.roblox.com/asset/?id=10341386932",
					["240"] = "http://www.roblox.com/asset/?id=10341393986",
					["245"] = "http://www.roblox.com/asset/?id=10341398805",
					["250-255"] = "http://www.roblox.com/asset/?id=10341402348",
				},
			},
		},
		[2] = {
			Name = "Accessories",
			Items = {
				["Blue Dutybelt"] = { "PoliceBelt" },
				["Staff Dutybelt"] = { "StaffPoliceBelt" },
			},
		},
		[3] = {
			Name = "Hairstyles",
			Items = {
				["Bun"] = { "Bun" },
				["Trecky"] = { "Trecky" },
			},
		},
	},

	SHERIFFS = {
		[1] = {
			Id = 7220365,
			Name = "Uniforms",
			Pants = "http://www.roblox.com/asset/?id=6201435672",
			Items = {
				["Polo"] = {
					["10-255"] = "http://www.roblox.com/asset/?id=6201436870",
				},
				["Class A"] = {
					["230"] = "http://www.roblox.com/asset/?id=6201437581",
					["215"] = "http://www.roblox.com/asset/?id=6201437884",
					["10-205"] = "http://www.roblox.com/asset/?id=6201438348",
					["210"] = "http://www.roblox.com/asset/?id=6201438846",
					["225"] = "http://www.roblox.com/asset/?id=6201439348",
					["220"] = "http://www.roblox.com/asset/?id=6201439835",
					["245-255"] = "http://www.roblox.com/asset/?id=6201440408",
					["240"] = "http://www.roblox.com/asset/?id=6201441844",
				},
				["Class B"] = {
					["230"] = "http://www.roblox.com/asset/?id=6201442913",
					["215"] = "http://www.roblox.com/asset/?id=6201443281",
					["10-205"] = "http://www.roblox.com/asset/?id=6201443658",
					["210"] = "http://www.roblox.com/asset/?id=6201444075",
					["225"] = "http://www.roblox.com/asset/?id=6201444483",
					["220"] = "http://www.roblox.com/asset/?id=6201444845",
					["245-255"] = "http://www.roblox.com/asset/?id=6201445156",
					["240"] = "http://www.roblox.com/asset/?id=6201445514",
				},
				["Class C"] = {
					["230"] = "http://www.roblox.com/asset/?id=6201446814",
					["215"] = "http://www.roblox.com/asset/?id=6201447239",
					["10-205"] = "http://www.roblox.com/asset/?id=6201447541",
					["210"] = "http://www.roblox.com/asset/?id=6201448142",
					["225"] = "http://www.roblox.com/asset/?id=6201448739",
					["220"] = "http://www.roblox.com/asset/?id=6201449124",
					["245-255"] = "http://www.roblox.com/asset/?id=6201449552",
					["240"] = "http://www.roblox.com/asset/?id=6201449907",
				},
			},
		},
		[2] = {
			Name = "Accessories",
			Items = {
				["Blue Dutybelt"] = { "PoliceBelt" },
				["Staff Dutybelt"] = { "StaffPoliceBelt" },
			},
		},
		[3] = {
			Name = "Hairstyles",
			Items = {
				["Bun"] = { "Bun" },
				["Trecky"] = { "Trecky" },
			},
		},
	},
}
